server:
  port: 8093
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://mysql:3306/dhmoney
    username: grupo9
    password: grupo9
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      dll-auto: update
    show-sql: true
    datasource:
      url: jdbc:mysql://mysql:3306/dhmoney
      username: grupo9
      password: grupo9
